name: Elson
favicon: null
layout_spectrum: 0.5011646680068225
typography_spectrum: 0.8035789204295725
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8402736803982407
  lightness: 0.4959675648715347
  saturation: 0.8459735340438783
  rhythmicContrast: 0.4114921160507947
purpose: []
